### ISSUE TITLE
#Задание 8. Глава 3

### ISSUE THREAD

**Issue by Chance20022** [Unrealized/lafore#10]
Подкорректируй ввод данных. Слишком объёмный, можешь посмотреть у меня. Слишком много всего там. Векторы, многочисленные циклы. Можно было и проще

**Comment by take-my-evolution** [comment]
Согласен насчёт того,  что можно проще. Но мне хотелось именно так. В других задачах использовал  варианты ввода попроще. Это  хочу оставить на память.
