### ISSUE TITLE
Задание 3 глава 4. 

### ISSUE THREAD

**Issue by Chance20022** [Unrealized/lafore#12]
Ну, немного странно, что ты на 33 строчке присвоил к ch 39.  Можно ж было написать в cout нужную тебе клавишу. И если расширить твою программу и при этом нужно будет работать дальше с этой переменной, то возможно возникили бы проблемы. Маловероятно, но всё же. Ну возможно просто докопался, но очень сильно режет глаза. И тут уже лично моя придирка, а может и нет, но суть в том, что всё же лучше выносить структуру за main, но как говорил Никита, если ты хотел сделать её локальной, то пожалуйста, а в остальных случаях, лучше так не делать. Ну тут не знаю. Короче вот

**Comment by NikitaDotIvanov64** [comment]
deleted magic number
