### ISSUE TITLE
#Задание 4.  Глава 3

### ISSUE THREAD

**Issue by Chance20022** [Unrealized/lafore#9]
Это конечно на твоё усмотрение, но в задании не написано, чтобы выводило то, что ввёл пользователь. Здесь как хочешь

**Comment by NikitaDotIvanov64** [comment]
Я бы вообще написал, 
std::cin >> a  >> ch >> b;
  
Вместо
std::cin >> a ;
  std::cout << "first operand " << a<<std::endl;
  std::cin >> ch ;
  std::cout << "operation is a  " << ch<<std::endl;
  std::cin >> b ;
  std::cout << "second operand " << b<<std::endl;
